import re
import platform
import requests
from bs4 import BeautifulSoup

# ============================================================
# CONFIG
# ============================================================

OUTPUT = "syscalls/generated_syscalls.hpp"

URL = "https://filippo.io/linux-syscall-table/"

# ------------------------------------------------------------
# ARCH DETECTION
# ------------------------------------------------------------

ARCH = platform.machine()

ARCH_HEADERS = {
    "x86_64": "/usr/include/asm/unistd_64.h",
    "aarch64": "/usr/include/asm/unistd.h",
}

if ARCH not in ARCH_HEADERS:
    raise RuntimeError(f"Unsupported architecture: {ARCH}")

UNISTD = ARCH_HEADERS[ARCH]

# ------------------------------------------------------------
# MANUAL SYSCALLS (NEVER GENERATE)
# ------------------------------------------------------------

SKIP = {
    "read",
    "write",
    "open",
    "openat",
    "close",

    "connect",
    "socket",
    "socketpair",

    "sendto",
    "recvfrom",

    "sendmsg",
    "recvmsg",

    "accept",
    "accept4",

    "dup",
    "dup2",
    "dup3",

    "pipe",
    "pipe2",

    "execve",
}

# ------------------------------------------------------------
# OPTIONAL ALLOW-LIST
# Leave empty to generate everything except SKIP.
# ------------------------------------------------------------

ALLOW = {
    # "mmap",
    # "munmap",
    # "brk",
    # "futex",
}

# ============================================================
# TYPE MAPPING
# ============================================================

def map_type(t: str) -> str:
    t = t.strip()

    # normalize
    t = t.replace("const ", "")
    t = t.replace("__user ", "")

    # strings
    if "char *" in t:
        return "CStringArg"

    # generic pointers
    if "*" in t:
        return "PtrArg"

    # sizes
    if "size_t" in t:
        return "SizeArg"

    # integers
    if (
        "int" in t
        or "long" in t
        or "short" in t
        or "unsigned" in t
        or "u32" in t
        or "u64" in t
    ):
        return "IntArg"

    # fallback
    return "PtrArg"

# ============================================================
# PARSE SYSCALL NUMBERS
# ============================================================

nr_map = {}

pattern = re.compile(r"#define __NR_(\w+)\s+(\d+)")

with open(UNISTD) as f:
    for line in f:
        m = pattern.match(line)

        if not m:
            continue

        name = m.group(1)
        nr = int(m.group(2))

        nr_map[name] = nr

# ============================================================
# SCRAPE ARGUMENT TYPES
# ============================================================

html = requests.get(URL).text

soup = BeautifulSoup(html, "html.parser")

rows = soup.select("tr")

arg_map = {}

i = 0

while i < len(rows):
    row = rows[i]

    classes = row.get("class", [])

    # syscall row
    if "tbls-entry-collapsed" in classes:
        cols = row.find_all("td")

        if len(cols) < 2:
            i += 1
            continue

        name = cols[1].text.strip()

        # skip custom handlers
        if name in SKIP:
            i += 2
            continue

        # allow-list support
        if ALLOW and name not in ALLOW:
            i += 2
            continue

        args = []

        # next row contains arguments
        if i + 1 < len(rows):
            arg_row = rows[i + 1]

            arg_classes = arg_row.get("class", [])

            if "tbls-arguments-collapsed" in arg_classes:

                arg_cells = arg_row.select(
                    "tbody tr:nth-of-type(2) td"
                )

                for cell in arg_cells:
                    text = cell.text.strip()

                    # remove variable name
                    parts = text.split()

                    if len(parts) > 1:
                        ctype = " ".join(parts[:-1])
                    else:
                        ctype = parts[0]

                    args.append(map_type(ctype))

        arg_map[name] = args

        i += 2
        continue

    i += 1

# ============================================================
# GENERATE HEADER
# ============================================================

generated = set()

with open(OUTPUT, "w") as out:

    out.write("// =====================================================\n")
    out.write("// AUTO-GENERATED FILE - DO NOT EDIT\n")
    out.write("// Generated by tools/gen_all_syscalls.py\n")
    out.write("// =====================================================\n\n")

    out.write("#pragma once\n\n")

    out.write('#include "../core/syscall.hpp"\n')
    out.write('#include "../core/register.hpp"\n')
    out.write('#include "../core/types.hpp"\n\n')

    for name, nr in sorted(nr_map.items(), key=lambda x: x[1]):

        if name in SKIP:
            continue

        if ALLOW and name not in ALLOW:
            continue

        if name in generated:
            continue

        generated.add(name)

        args = arg_map.get(name, [])

        struct_name = "".join(
            part.capitalize()
            for part in name.split("_")
        ) + "Syscall"

        arg_str = ""

        if args:
            arg_str = ", " + ", ".join(args)

        out.write(
            f"struct {struct_name} : "
            f"Syscall<{struct_name}, {nr}{arg_str}>\n"
        )

        out.write("{\n")

        out.write(
            f'    static const char *name() {{ return "{name}"; }}\n'
        )

        out.write("};\n\n")

        out.write(
            f"static Register<{struct_name}> "
            f"reg_{name};\n\n"
        )

print(f"✅ Generated {len(generated)} syscalls.")